@startuml CLD_OTOS
title Class Diagram for **OTOS**\n

hide empty members

class Thread {
    'Properties:
    + Stack_pointer
    - Stacksize
    - Stack_top
    - priority
    - schedule_ticks
    - counter_ticks

    'Methods:
    + Thread()
    + set_stack()
    + get_stacksize()
    + get_stackoverflow()
    + set_schedule()
    + count_tick()
    + is_runable()
}
class Kernel{
    'Properties:
    - active_thread
    - thread_count
    - Thread[NUMBER_THREADS]
    - Stack[StackSize]
    - //static// Time_ms

    'Methods:
    + Kernel()
    + schedule_thread()
    + start()
    + get_allocated_stacksize()
    + //static// count_time_ms()
    + //static// get_time_ms()
    - update_schedule()
    - get_next_thread()
    - switch_thread()
}

class Watchdog {
   '+ Watchdog()
   '+ Pet()
}

class Task{
    ' Properties:
    - LastTicks

    ' Methods:
    + Task()
    ' + //static// Lock()
    ' + //static// Unlock()
    ' + //static// WaitFor()
    + //static// Yield()
    ' + Sleep()
    ' - GetSysTick()
}

class IPC{
   '- Id
   '- CmdBuffer
   '+ GetQueue()
   '+ PushQueue()
}

Thread "*"-*"1" Kernel
Kernel --|> Watchdog
Task --|> IPC

@enduml