@startuml CLD_OTOS
title Class Diagram for **OTOS**\n

hide empty members

class Schedule{
    'Properties:
    - ThreadPriority
    - TickSchedule
    - TickCounter

    'Methods
    + Schedule()
    + setSchedule()
    + countTick()
    + isRunable()
}

class Thread {
    'Properies:
    - StackSize
    - StackTop
    + StackPointer

    'Methods:
    + Thread()
    + setStack()
    + getStackSize()
    + getStackOverflow()
}
class Kernel{
    'Properties:
    - CurrentThread
    - ThreadCount
    - Thread[NUMBER_THREADS]
    - Stack[StackSize]

    'Methods:
    + Kernel()
    + scheduleThread()
    ' + ScheduleThread_Hz()
    + start()
    - updateSchedule()
    - getNextThread()
    - switchThread()
    ' - time_ms()
}

class Watchdog {
   '+ Watchdog()
   '+ Pet()
}

class Task{
    ' Properties:
    - LastTicks

    ' Methods:
    + Task()
    + //static// Lock()
    + //static// Unlock()
    + //static// WaitFor()
    + //static// Yield()
    + Sleep()
    - GetSysTick()
}

class IPC{
   '- Id
   '- CmdBuffer
   '+ GetQueue()
   '+ PushQueue()
}

Thread --|> Schedule
Thread "*"-*"1" Kernel
Kernel --|> Watchdog
Task --|> IPC

@enduml