@startuml STA_Thread
title State Diagram of Threads\n
caption OTOS

[*] --> Runnable
Runnable --> Running: Execute Thread
Running --> Blocked: Finished Execution
Blocked --> Runnable: Schedule is Valid
Blocked --> Inactive: Error occured
Blocked --> Inactive: Set Inactive
Running --> Inactive: Set Inactive
Inactive --> Blocked: Set Active

@enduml