@startuml STA_Thread
title State Diagram of Threads\n
caption OTOS

[*] --> Runable
Runable --> Running: Execute Thread
Running --> Blocked: Finished Execution
Blocked --> Runable: Schedule is Valid
Blocked --> Suspended: Error occured

@enduml