@startwbs WBS_LibStructure
title The Library Structure within **OTOS** \n
legend Hardware or Processor specific levels are marked in **<color #SkyBlue> blue </color>**.\n<b>Dependent</b> libraries are included without a surrounding box.

*_ lib

' === Kernel ===
**[#GreenYellow] kernel
*** kernel.h
****_ processors.h
' *** schedule.h
*** types.h
*** thread.h

' === Task ===
**[#GreenYellow] task
*** task.h
****_ processors.h
*** ipc.h
*** error_codes.h

' === Processors ===
**[#GreenYellow] processors
*** processors.h
****_ vendors.h
****[#SkyBlue] arm_cm0plus_nofpu.h
****[#SkyBlue] arm_cm4_nofpu.h

' === Vendors ===
**[#GreenYellow] vendors
*** vendors.h
****_ stm32f4xx.h
****_ stm32l0xx.h

' === Drivers ===
**[#GreenYellow] drivers
*** interface.h
****_ error_codes.h
*** drivers.h
****_ battery
*****[#SkyBlue] bq25700.h
*****[#SkyBlue] max17205.h
*****[#SkyBlue] tps65987.h
****_ display
*****[#SkyBlue] ssd1306.h
*****[#SkyBlue] ili9341.h
*****[#SkyBlue] uc1611.h
****_ stm32
*****[#SkyBlue] core_stm32.h
*****[#SkyBlue] gpio_stm32.h
*****[#SkyBlue] i2c_stm32.h
*****[#SkyBlue] spi_stm32.h
*****[#SkyBlue] sdio_stm32.h
*****[#SkyBlue] timer_stm32.h
*****[#SkyBlue] usart_stm32.h

' === Graphics ===
**[#GreenYellow] graphics
*** graphics.h
*** font.h

' === Files ===
**[#GreenYellow] files
*** file.h 
*** drive.h 
***_ memory 
**** sdhc.h
*****_ interface.h
***_ filesystem
**** fat32.h

@endwbs