@startwbs WBS_Functions
title Main Function Breakdown of OTOS\n

* **OTOS**
** Threads
*** Scheduling
**** Switching
**** Prioritising
**** Timing
*** Stack Overflow

** Kernel
*** Watchdog
*** Error Handling
*** Logging

@endwbs